/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicLayoutRouteImport } from './routes/_public/layout'
import { Route as HealthRouteImport } from './routes/health'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicSplatRouteImport } from './routes/_public/$'
import { Route as PublicContatoRouteImport } from './routes/_public/contato'
import { Route as PublicFestivalRouteImport } from './routes/_public/festival'
import { Route as PublicPrivacidadeRouteImport } from './routes/_public/privacidade'
import { Route as PublicSocioRouteImport } from './routes/_public/socio'
import { Route as PublicTemaRouteImport } from './routes/_public/tema'
import { Route as PublicTermosRouteImport } from './routes/_public/termos'
import { Route as PublicVisiteRouteImport } from './routes/_public/visite'
import { Route as PublicAgendaIndexRouteImport } from './routes/_public/agenda/index'
import { Route as PublicBoiGaleriaRouteImport } from './routes/_public/boi/galeria'
import { Route as PublicBoiHistoriaRouteImport } from './routes/_public/boi/historia'
import { Route as PublicBoiItensRouteImport } from './routes/_public/boi/itens'
import { Route as PublicBoiToadasRouteImport } from './routes/_public/boi/toadas'
import { Route as PublicLojaIndexRouteImport } from './routes/_public/loja/index'
import { Route as PublicLojaBuscaRouteImport } from './routes/_public/loja/busca'
import { Route as PublicLojaCarrinhoRouteImport } from './routes/_public/loja/carrinho'
import { Route as PublicLojaCheckoutRouteImport } from './routes/_public/loja/checkout'
import { Route as PublicNoticiasIndexRouteImport } from './routes/_public/noticias/index'
import { Route as PublicLojaAjudaIndexRouteImport } from './routes/_public/loja/ajuda/index'
import { Route as PublicLojaAjudaSlugRouteImport } from './routes/_public/loja/ajuda/$slug'
import { Route as PublicLojaCategoriaSlugRouteImport } from './routes/_public/loja/categoria/$slug'
import { Route as PublicLojaPedidoCodeRouteImport } from './routes/_public/loja/pedido/$code'
import { Route as PublicLojaProdutoSlugRouteImport } from './routes/_public/loja/produto/$slug'

const PublicLayoutRoute = PublicLayoutRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicLayoutRoute,
} as any).lazy(() => import('./routes/_public/index.lazy').then((d) => d.Route))
const PublicSplatRoute = PublicSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => PublicLayoutRoute,
} as any)
const PublicContatoRoute = PublicContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => PublicLayoutRoute,
} as any)
const PublicFestivalRoute = PublicFestivalRouteImport.update({
  id: '/festival',
  path: '/festival',
  getParentRoute: () => PublicLayoutRoute,
} as any)
const PublicPrivacidadeRoute = PublicPrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => PublicLayoutRoute,
} as any)
const PublicSocioRoute = PublicSocioRouteImport.update({
  id: '/socio',
  path: '/socio',
  getParentRoute: () => PublicLayoutRoute,
} as any)
const PublicTemaRoute = PublicTemaRouteImport.update({
  id: '/tema',
  path: '/tema',
  getParentRoute: () => PublicLayoutRoute,
} as any)
const PublicTermosRoute = PublicTermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => PublicLayoutRoute,
} as any)
const PublicVisiteRoute = PublicVisiteRouteImport.update({
  id: '/visite',
  path: '/visite',
  getParentRoute: () => PublicLayoutRoute,
} as any)
const PublicAgendaIndexRoute = PublicAgendaIndexRouteImport.update({
  id: '/agenda/',
  path: '/agenda/',
  getParentRoute: () => PublicLayoutRoute,
} as any)
const PublicBoiGaleriaRoute = PublicBoiGaleriaRouteImport.update({
  id: '/boi/galeria',
  path: '/boi/galeria',
  getParentRoute: () => PublicLayoutRoute,
} as any)
const PublicBoiHistoriaRoute = PublicBoiHistoriaRouteImport.update({
  id: '/boi/historia',
  path: '/boi/historia',
  getParentRoute: () => PublicLayoutRoute,
} as any)
const PublicBoiItensRoute = PublicBoiItensRouteImport.update({
  id: '/boi/itens',
  path: '/boi/itens',
  getParentRoute: () => PublicLayoutRoute,
} as any)
const PublicBoiToadasRoute = PublicBoiToadasRouteImport.update({
  id: '/boi/toadas',
  path: '/boi/toadas',
  getParentRoute: () => PublicLayoutRoute,
} as any)
const PublicLojaIndexRoute = PublicLojaIndexRouteImport.update({
  id: '/loja/',
  path: '/loja/',
  getParentRoute: () => PublicLayoutRoute,
} as any).lazy(() =>
  import('./routes/_public/loja/index.lazy').then((d) => d.Route),
)
const PublicLojaBuscaRoute = PublicLojaBuscaRouteImport.update({
  id: '/loja/busca',
  path: '/loja/busca',
  getParentRoute: () => PublicLayoutRoute,
} as any).lazy(() =>
  import('./routes/_public/loja/busca.lazy').then((d) => d.Route),
)
const PublicLojaCarrinhoRoute = PublicLojaCarrinhoRouteImport.update({
  id: '/loja/carrinho',
  path: '/loja/carrinho',
  getParentRoute: () => PublicLayoutRoute,
} as any).lazy(() =>
  import('./routes/_public/loja/carrinho.lazy').then((d) => d.Route),
)
const PublicLojaCheckoutRoute = PublicLojaCheckoutRouteImport.update({
  id: '/loja/checkout',
  path: '/loja/checkout',
  getParentRoute: () => PublicLayoutRoute,
} as any).lazy(() =>
  import('./routes/_public/loja/checkout.lazy').then((d) => d.Route),
)
const PublicNoticiasIndexRoute = PublicNoticiasIndexRouteImport.update({
  id: '/noticias/',
  path: '/noticias/',
  getParentRoute: () => PublicLayoutRoute,
} as any)
const PublicLojaAjudaIndexRoute = PublicLojaAjudaIndexRouteImport.update({
  id: '/loja/ajuda/',
  path: '/loja/ajuda/',
  getParentRoute: () => PublicLayoutRoute,
} as any).lazy(() =>
  import('./routes/_public/loja/ajuda/index.lazy').then((d) => d.Route),
)
const PublicLojaAjudaSlugRoute = PublicLojaAjudaSlugRouteImport.update({
  id: '/loja/ajuda/$slug',
  path: '/loja/ajuda/$slug',
  getParentRoute: () => PublicLayoutRoute,
} as any).lazy(() =>
  import('./routes/_public/loja/ajuda/$slug.lazy').then((d) => d.Route),
)
const PublicLojaCategoriaSlugRoute = PublicLojaCategoriaSlugRouteImport.update({
  id: '/loja/categoria/$slug',
  path: '/loja/categoria/$slug',
  getParentRoute: () => PublicLayoutRoute,
} as any).lazy(() =>
  import('./routes/_public/loja/categoria/$slug.lazy').then((d) => d.Route),
)
const PublicLojaPedidoCodeRoute = PublicLojaPedidoCodeRouteImport.update({
  id: '/loja/pedido/$code',
  path: '/loja/pedido/$code',
  getParentRoute: () => PublicLayoutRoute,
} as any).lazy(() =>
  import('./routes/_public/loja/pedido/$code.lazy').then((d) => d.Route),
)
const PublicLojaProdutoSlugRoute = PublicLojaProdutoSlugRouteImport.update({
  id: '/loja/produto/$slug',
  path: '/loja/produto/$slug',
  getParentRoute: () => PublicLayoutRoute,
} as any).lazy(() =>
  import('./routes/_public/loja/produto/$slug.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/health': typeof HealthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$': typeof PublicSplatRoute
  '/contato': typeof PublicContatoRoute
  '/festival': typeof PublicFestivalRoute
  '/privacidade': typeof PublicPrivacidadeRoute
  '/socio': typeof PublicSocioRoute
  '/tema': typeof PublicTemaRoute
  '/termos': typeof PublicTermosRoute
  '/visite': typeof PublicVisiteRoute
  '/boi/galeria': typeof PublicBoiGaleriaRoute
  '/boi/historia': typeof PublicBoiHistoriaRoute
  '/boi/itens': typeof PublicBoiItensRoute
  '/boi/toadas': typeof PublicBoiToadasRoute
  '/loja/busca': typeof PublicLojaBuscaRoute
  '/loja/carrinho': typeof PublicLojaCarrinhoRoute
  '/loja/checkout': typeof PublicLojaCheckoutRoute
  '/agenda/': typeof PublicAgendaIndexRoute
  '/loja/': typeof PublicLojaIndexRoute
  '/noticias/': typeof PublicNoticiasIndexRoute
  '/loja/ajuda/$slug': typeof PublicLojaAjudaSlugRoute
  '/loja/categoria/$slug': typeof PublicLojaCategoriaSlugRoute
  '/loja/pedido/$code': typeof PublicLojaPedidoCodeRoute
  '/loja/produto/$slug': typeof PublicLojaProdutoSlugRoute
  '/loja/ajuda/': typeof PublicLojaAjudaIndexRoute
}
export interface FileRoutesByTo {
  '/health': typeof HealthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$': typeof PublicSplatRoute
  '/contato': typeof PublicContatoRoute
  '/festival': typeof PublicFestivalRoute
  '/privacidade': typeof PublicPrivacidadeRoute
  '/socio': typeof PublicSocioRoute
  '/tema': typeof PublicTemaRoute
  '/termos': typeof PublicTermosRoute
  '/visite': typeof PublicVisiteRoute
  '/': typeof PublicIndexRoute
  '/boi/galeria': typeof PublicBoiGaleriaRoute
  '/boi/historia': typeof PublicBoiHistoriaRoute
  '/boi/itens': typeof PublicBoiItensRoute
  '/boi/toadas': typeof PublicBoiToadasRoute
  '/loja/busca': typeof PublicLojaBuscaRoute
  '/loja/carrinho': typeof PublicLojaCarrinhoRoute
  '/loja/checkout': typeof PublicLojaCheckoutRoute
  '/agenda': typeof PublicAgendaIndexRoute
  '/loja': typeof PublicLojaIndexRoute
  '/noticias': typeof PublicNoticiasIndexRoute
  '/loja/ajuda/$slug': typeof PublicLojaAjudaSlugRoute
  '/loja/categoria/$slug': typeof PublicLojaCategoriaSlugRoute
  '/loja/pedido/$code': typeof PublicLojaPedidoCodeRoute
  '/loja/produto/$slug': typeof PublicLojaProdutoSlugRoute
  '/loja/ajuda': typeof PublicLojaAjudaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicLayoutRouteWithChildren
  '/health': typeof HealthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_public/$': typeof PublicSplatRoute
  '/_public/contato': typeof PublicContatoRoute
  '/_public/festival': typeof PublicFestivalRoute
  '/_public/privacidade': typeof PublicPrivacidadeRoute
  '/_public/socio': typeof PublicSocioRoute
  '/_public/tema': typeof PublicTemaRoute
  '/_public/termos': typeof PublicTermosRoute
  '/_public/visite': typeof PublicVisiteRoute
  '/_public/': typeof PublicIndexRoute
  '/_public/boi/galeria': typeof PublicBoiGaleriaRoute
  '/_public/boi/historia': typeof PublicBoiHistoriaRoute
  '/_public/boi/itens': typeof PublicBoiItensRoute
  '/_public/boi/toadas': typeof PublicBoiToadasRoute
  '/_public/loja/busca': typeof PublicLojaBuscaRoute
  '/_public/loja/carrinho': typeof PublicLojaCarrinhoRoute
  '/_public/loja/checkout': typeof PublicLojaCheckoutRoute
  '/_public/agenda/': typeof PublicAgendaIndexRoute
  '/_public/loja/': typeof PublicLojaIndexRoute
  '/_public/noticias/': typeof PublicNoticiasIndexRoute
  '/_public/loja/ajuda/$slug': typeof PublicLojaAjudaSlugRoute
  '/_public/loja/categoria/$slug': typeof PublicLojaCategoriaSlugRoute
  '/_public/loja/pedido/$code': typeof PublicLojaPedidoCodeRoute
  '/_public/loja/produto/$slug': typeof PublicLojaProdutoSlugRoute
  '/_public/loja/ajuda/': typeof PublicLojaAjudaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/health'
    | '/sitemap.xml'
    | '/$'
    | '/contato'
    | '/festival'
    | '/privacidade'
    | '/socio'
    | '/tema'
    | '/termos'
    | '/visite'
    | '/boi/galeria'
    | '/boi/historia'
    | '/boi/itens'
    | '/boi/toadas'
    | '/loja/busca'
    | '/loja/carrinho'
    | '/loja/checkout'
    | '/agenda/'
    | '/loja/'
    | '/noticias/'
    | '/loja/ajuda/$slug'
    | '/loja/categoria/$slug'
    | '/loja/pedido/$code'
    | '/loja/produto/$slug'
    | '/loja/ajuda/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/health'
    | '/sitemap.xml'
    | '/$'
    | '/contato'
    | '/festival'
    | '/privacidade'
    | '/socio'
    | '/tema'
    | '/termos'
    | '/visite'
    | '/'
    | '/boi/galeria'
    | '/boi/historia'
    | '/boi/itens'
    | '/boi/toadas'
    | '/loja/busca'
    | '/loja/carrinho'
    | '/loja/checkout'
    | '/agenda'
    | '/loja'
    | '/noticias'
    | '/loja/ajuda/$slug'
    | '/loja/categoria/$slug'
    | '/loja/pedido/$code'
    | '/loja/produto/$slug'
    | '/loja/ajuda'
  id:
    | '__root__'
    | '/_public'
    | '/health'
    | '/sitemap.xml'
    | '/_public/$'
    | '/_public/contato'
    | '/_public/festival'
    | '/_public/privacidade'
    | '/_public/socio'
    | '/_public/tema'
    | '/_public/termos'
    | '/_public/visite'
    | '/_public/'
    | '/_public/boi/galeria'
    | '/_public/boi/historia'
    | '/_public/boi/itens'
    | '/_public/boi/toadas'
    | '/_public/loja/busca'
    | '/_public/loja/carrinho'
    | '/_public/loja/checkout'
    | '/_public/agenda/'
    | '/_public/loja/'
    | '/_public/noticias/'
    | '/_public/loja/ajuda/$slug'
    | '/_public/loja/categoria/$slug'
    | '/_public/loja/pedido/$code'
    | '/_public/loja/produto/$slug'
    | '/_public/loja/ajuda/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicLayoutRoute: typeof PublicLayoutRouteWithChildren
  HealthRoute: typeof HealthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_public/$': {
      id: '/_public/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof PublicSplatRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_public/contato': {
      id: '/_public/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof PublicContatoRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_public/festival': {
      id: '/_public/festival'
      path: '/festival'
      fullPath: '/festival'
      preLoaderRoute: typeof PublicFestivalRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_public/privacidade': {
      id: '/_public/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PublicPrivacidadeRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_public/socio': {
      id: '/_public/socio'
      path: '/socio'
      fullPath: '/socio'
      preLoaderRoute: typeof PublicSocioRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_public/tema': {
      id: '/_public/tema'
      path: '/tema'
      fullPath: '/tema'
      preLoaderRoute: typeof PublicTemaRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_public/termos': {
      id: '/_public/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof PublicTermosRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_public/visite': {
      id: '/_public/visite'
      path: '/visite'
      fullPath: '/visite'
      preLoaderRoute: typeof PublicVisiteRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_public/agenda/': {
      id: '/_public/agenda/'
      path: '/agenda'
      fullPath: '/agenda/'
      preLoaderRoute: typeof PublicAgendaIndexRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_public/boi/galeria': {
      id: '/_public/boi/galeria'
      path: '/boi/galeria'
      fullPath: '/boi/galeria'
      preLoaderRoute: typeof PublicBoiGaleriaRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_public/boi/historia': {
      id: '/_public/boi/historia'
      path: '/boi/historia'
      fullPath: '/boi/historia'
      preLoaderRoute: typeof PublicBoiHistoriaRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_public/boi/itens': {
      id: '/_public/boi/itens'
      path: '/boi/itens'
      fullPath: '/boi/itens'
      preLoaderRoute: typeof PublicBoiItensRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_public/boi/toadas': {
      id: '/_public/boi/toadas'
      path: '/boi/toadas'
      fullPath: '/boi/toadas'
      preLoaderRoute: typeof PublicBoiToadasRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_public/loja/': {
      id: '/_public/loja/'
      path: '/loja'
      fullPath: '/loja/'
      preLoaderRoute: typeof PublicLojaIndexRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_public/loja/busca': {
      id: '/_public/loja/busca'
      path: '/loja/busca'
      fullPath: '/loja/busca'
      preLoaderRoute: typeof PublicLojaBuscaRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_public/loja/carrinho': {
      id: '/_public/loja/carrinho'
      path: '/loja/carrinho'
      fullPath: '/loja/carrinho'
      preLoaderRoute: typeof PublicLojaCarrinhoRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_public/loja/checkout': {
      id: '/_public/loja/checkout'
      path: '/loja/checkout'
      fullPath: '/loja/checkout'
      preLoaderRoute: typeof PublicLojaCheckoutRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_public/noticias/': {
      id: '/_public/noticias/'
      path: '/noticias'
      fullPath: '/noticias/'
      preLoaderRoute: typeof PublicNoticiasIndexRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_public/loja/ajuda/': {
      id: '/_public/loja/ajuda/'
      path: '/loja/ajuda'
      fullPath: '/loja/ajuda/'
      preLoaderRoute: typeof PublicLojaAjudaIndexRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_public/loja/ajuda/$slug': {
      id: '/_public/loja/ajuda/$slug'
      path: '/loja/ajuda/$slug'
      fullPath: '/loja/ajuda/$slug'
      preLoaderRoute: typeof PublicLojaAjudaSlugRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_public/loja/categoria/$slug': {
      id: '/_public/loja/categoria/$slug'
      path: '/loja/categoria/$slug'
      fullPath: '/loja/categoria/$slug'
      preLoaderRoute: typeof PublicLojaCategoriaSlugRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_public/loja/pedido/$code': {
      id: '/_public/loja/pedido/$code'
      path: '/loja/pedido/$code'
      fullPath: '/loja/pedido/$code'
      preLoaderRoute: typeof PublicLojaPedidoCodeRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_public/loja/produto/$slug': {
      id: '/_public/loja/produto/$slug'
      path: '/loja/produto/$slug'
      fullPath: '/loja/produto/$slug'
      preLoaderRoute: typeof PublicLojaProdutoSlugRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
  }
}

interface PublicLayoutRouteChildren {
  PublicSplatRoute: typeof PublicSplatRoute
  PublicContatoRoute: typeof PublicContatoRoute
  PublicFestivalRoute: typeof PublicFestivalRoute
  PublicPrivacidadeRoute: typeof PublicPrivacidadeRoute
  PublicSocioRoute: typeof PublicSocioRoute
  PublicTemaRoute: typeof PublicTemaRoute
  PublicTermosRoute: typeof PublicTermosRoute
  PublicVisiteRoute: typeof PublicVisiteRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicBoiGaleriaRoute: typeof PublicBoiGaleriaRoute
  PublicBoiHistoriaRoute: typeof PublicBoiHistoriaRoute
  PublicBoiItensRoute: typeof PublicBoiItensRoute
  PublicBoiToadasRoute: typeof PublicBoiToadasRoute
  PublicLojaBuscaRoute: typeof PublicLojaBuscaRoute
  PublicLojaCarrinhoRoute: typeof PublicLojaCarrinhoRoute
  PublicLojaCheckoutRoute: typeof PublicLojaCheckoutRoute
  PublicAgendaIndexRoute: typeof PublicAgendaIndexRoute
  PublicLojaIndexRoute: typeof PublicLojaIndexRoute
  PublicNoticiasIndexRoute: typeof PublicNoticiasIndexRoute
  PublicLojaAjudaSlugRoute: typeof PublicLojaAjudaSlugRoute
  PublicLojaCategoriaSlugRoute: typeof PublicLojaCategoriaSlugRoute
  PublicLojaPedidoCodeRoute: typeof PublicLojaPedidoCodeRoute
  PublicLojaProdutoSlugRoute: typeof PublicLojaProdutoSlugRoute
  PublicLojaAjudaIndexRoute: typeof PublicLojaAjudaIndexRoute
}

const PublicLayoutRouteChildren: PublicLayoutRouteChildren = {
  PublicSplatRoute: PublicSplatRoute,
  PublicContatoRoute: PublicContatoRoute,
  PublicFestivalRoute: PublicFestivalRoute,
  PublicPrivacidadeRoute: PublicPrivacidadeRoute,
  PublicSocioRoute: PublicSocioRoute,
  PublicTemaRoute: PublicTemaRoute,
  PublicTermosRoute: PublicTermosRoute,
  PublicVisiteRoute: PublicVisiteRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicBoiGaleriaRoute: PublicBoiGaleriaRoute,
  PublicBoiHistoriaRoute: PublicBoiHistoriaRoute,
  PublicBoiItensRoute: PublicBoiItensRoute,
  PublicBoiToadasRoute: PublicBoiToadasRoute,
  PublicLojaBuscaRoute: PublicLojaBuscaRoute,
  PublicLojaCarrinhoRoute: PublicLojaCarrinhoRoute,
  PublicLojaCheckoutRoute: PublicLojaCheckoutRoute,
  PublicAgendaIndexRoute: PublicAgendaIndexRoute,
  PublicLojaIndexRoute: PublicLojaIndexRoute,
  PublicNoticiasIndexRoute: PublicNoticiasIndexRoute,
  PublicLojaAjudaSlugRoute: PublicLojaAjudaSlugRoute,
  PublicLojaCategoriaSlugRoute: PublicLojaCategoriaSlugRoute,
  PublicLojaPedidoCodeRoute: PublicLojaPedidoCodeRoute,
  PublicLojaProdutoSlugRoute: PublicLojaProdutoSlugRoute,
  PublicLojaAjudaIndexRoute: PublicLojaAjudaIndexRoute,
}

const PublicLayoutRouteWithChildren = PublicLayoutRoute._addFileChildren(
  PublicLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  PublicLayoutRoute: PublicLayoutRouteWithChildren,
  HealthRoute: HealthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
