/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticationLayoutRouteImport } from './routes/_authentication/layout'
import { Route as PrivateLayoutRouteImport } from './routes/_private/layout'
import { Route as PublicLayoutRouteImport } from './routes/_public/layout'
import { Route as HealthRouteImport } from './routes/health'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthenticationEntrarRouteImport } from './routes/_authentication/entrar'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicSplatRouteImport } from './routes/_public/$'
import { Route as PublicContatoRouteImport } from './routes/_public/contato'
import { Route as PublicFestivalRouteImport } from './routes/_public/festival'
import { Route as PublicPrivacidadeRouteImport } from './routes/_public/privacidade'
import { Route as PublicSocioRouteImport } from './routes/_public/socio'
import { Route as PublicTemaRouteImport } from './routes/_public/tema'
import { Route as PublicTermosRouteImport } from './routes/_public/termos'
import { Route as PublicVisiteRouteImport } from './routes/_public/visite'
import { Route as PrivatePainelIndexRouteImport } from './routes/_private/painel/index'
import { Route as PublicAgendaIndexRouteImport } from './routes/_public/agenda/index'
import { Route as PublicBoiGaleriaRouteImport } from './routes/_public/boi/galeria'
import { Route as PublicBoiHistoriaRouteImport } from './routes/_public/boi/historia'
import { Route as PublicBoiItensRouteImport } from './routes/_public/boi/itens'
import { Route as PublicBoiToadasRouteImport } from './routes/_public/boi/toadas'
import { Route as PublicLojaIndexRouteImport } from './routes/_public/loja/index'
import { Route as PublicLojaCarrinhoRouteImport } from './routes/_public/loja/carrinho'
import { Route as PublicNoticiasIndexRouteImport } from './routes/_public/noticias/index'

const AuthenticationLayoutRoute = AuthenticationLayoutRouteImport.update({
  id: '/_authentication',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateLayoutRoute = PrivateLayoutRouteImport.update({
  id: '/_private',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicLayoutRoute = PublicLayoutRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticationEntrarRoute = AuthenticationEntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => AuthenticationLayoutRoute,
} as any).lazy(() =>
  import('./routes/_authentication/entrar.lazy').then((d) => d.Route),
)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicLayoutRoute,
} as any).lazy(() => import('./routes/_public/index.lazy').then((d) => d.Route))
const PublicSplatRoute = PublicSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => PublicLayoutRoute,
} as any)
const PublicContatoRoute = PublicContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => PublicLayoutRoute,
} as any)
const PublicFestivalRoute = PublicFestivalRouteImport.update({
  id: '/festival',
  path: '/festival',
  getParentRoute: () => PublicLayoutRoute,
} as any)
const PublicPrivacidadeRoute = PublicPrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => PublicLayoutRoute,
} as any)
const PublicSocioRoute = PublicSocioRouteImport.update({
  id: '/socio',
  path: '/socio',
  getParentRoute: () => PublicLayoutRoute,
} as any)
const PublicTemaRoute = PublicTemaRouteImport.update({
  id: '/tema',
  path: '/tema',
  getParentRoute: () => PublicLayoutRoute,
} as any)
const PublicTermosRoute = PublicTermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => PublicLayoutRoute,
} as any)
const PublicVisiteRoute = PublicVisiteRouteImport.update({
  id: '/visite',
  path: '/visite',
  getParentRoute: () => PublicLayoutRoute,
} as any)
const PrivatePainelIndexRoute = PrivatePainelIndexRouteImport.update({
  id: '/painel/',
  path: '/painel/',
  getParentRoute: () => PrivateLayoutRoute,
} as any).lazy(() =>
  import('./routes/_private/painel/index.lazy').then((d) => d.Route),
)
const PublicAgendaIndexRoute = PublicAgendaIndexRouteImport.update({
  id: '/agenda/',
  path: '/agenda/',
  getParentRoute: () => PublicLayoutRoute,
} as any)
const PublicBoiGaleriaRoute = PublicBoiGaleriaRouteImport.update({
  id: '/boi/galeria',
  path: '/boi/galeria',
  getParentRoute: () => PublicLayoutRoute,
} as any)
const PublicBoiHistoriaRoute = PublicBoiHistoriaRouteImport.update({
  id: '/boi/historia',
  path: '/boi/historia',
  getParentRoute: () => PublicLayoutRoute,
} as any)
const PublicBoiItensRoute = PublicBoiItensRouteImport.update({
  id: '/boi/itens',
  path: '/boi/itens',
  getParentRoute: () => PublicLayoutRoute,
} as any)
const PublicBoiToadasRoute = PublicBoiToadasRouteImport.update({
  id: '/boi/toadas',
  path: '/boi/toadas',
  getParentRoute: () => PublicLayoutRoute,
} as any)
const PublicLojaIndexRoute = PublicLojaIndexRouteImport.update({
  id: '/loja/',
  path: '/loja/',
  getParentRoute: () => PublicLayoutRoute,
} as any)
const PublicLojaCarrinhoRoute = PublicLojaCarrinhoRouteImport.update({
  id: '/loja/carrinho',
  path: '/loja/carrinho',
  getParentRoute: () => PublicLayoutRoute,
} as any)
const PublicNoticiasIndexRoute = PublicNoticiasIndexRouteImport.update({
  id: '/noticias/',
  path: '/noticias/',
  getParentRoute: () => PublicLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/health': typeof HealthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/entrar': typeof AuthenticationEntrarRoute
  '/$': typeof PublicSplatRoute
  '/contato': typeof PublicContatoRoute
  '/festival': typeof PublicFestivalRoute
  '/privacidade': typeof PublicPrivacidadeRoute
  '/socio': typeof PublicSocioRoute
  '/tema': typeof PublicTemaRoute
  '/termos': typeof PublicTermosRoute
  '/visite': typeof PublicVisiteRoute
  '/boi/galeria': typeof PublicBoiGaleriaRoute
  '/boi/historia': typeof PublicBoiHistoriaRoute
  '/boi/itens': typeof PublicBoiItensRoute
  '/boi/toadas': typeof PublicBoiToadasRoute
  '/loja/carrinho': typeof PublicLojaCarrinhoRoute
  '/painel/': typeof PrivatePainelIndexRoute
  '/agenda/': typeof PublicAgendaIndexRoute
  '/loja/': typeof PublicLojaIndexRoute
  '/noticias/': typeof PublicNoticiasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/health': typeof HealthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/entrar': typeof AuthenticationEntrarRoute
  '/$': typeof PublicSplatRoute
  '/contato': typeof PublicContatoRoute
  '/festival': typeof PublicFestivalRoute
  '/privacidade': typeof PublicPrivacidadeRoute
  '/socio': typeof PublicSocioRoute
  '/tema': typeof PublicTemaRoute
  '/termos': typeof PublicTermosRoute
  '/visite': typeof PublicVisiteRoute
  '/boi/galeria': typeof PublicBoiGaleriaRoute
  '/boi/historia': typeof PublicBoiHistoriaRoute
  '/boi/itens': typeof PublicBoiItensRoute
  '/boi/toadas': typeof PublicBoiToadasRoute
  '/loja/carrinho': typeof PublicLojaCarrinhoRoute
  '/painel': typeof PrivatePainelIndexRoute
  '/agenda': typeof PublicAgendaIndexRoute
  '/loja': typeof PublicLojaIndexRoute
  '/noticias': typeof PublicNoticiasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authentication': typeof AuthenticationLayoutRouteWithChildren
  '/_private': typeof PrivateLayoutRouteWithChildren
  '/_public': typeof PublicLayoutRouteWithChildren
  '/health': typeof HealthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authentication/entrar': typeof AuthenticationEntrarRoute
  '/_public/$': typeof PublicSplatRoute
  '/_public/contato': typeof PublicContatoRoute
  '/_public/festival': typeof PublicFestivalRoute
  '/_public/privacidade': typeof PublicPrivacidadeRoute
  '/_public/socio': typeof PublicSocioRoute
  '/_public/tema': typeof PublicTemaRoute
  '/_public/termos': typeof PublicTermosRoute
  '/_public/visite': typeof PublicVisiteRoute
  '/_public/': typeof PublicIndexRoute
  '/_public/boi/galeria': typeof PublicBoiGaleriaRoute
  '/_public/boi/historia': typeof PublicBoiHistoriaRoute
  '/_public/boi/itens': typeof PublicBoiItensRoute
  '/_public/boi/toadas': typeof PublicBoiToadasRoute
  '/_public/loja/carrinho': typeof PublicLojaCarrinhoRoute
  '/_private/painel/': typeof PrivatePainelIndexRoute
  '/_public/agenda/': typeof PublicAgendaIndexRoute
  '/_public/loja/': typeof PublicLojaIndexRoute
  '/_public/noticias/': typeof PublicNoticiasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/health'
    | '/sitemap.xml'
    | '/entrar'
    | '/$'
    | '/contato'
    | '/festival'
    | '/privacidade'
    | '/socio'
    | '/tema'
    | '/termos'
    | '/visite'
    | '/boi/galeria'
    | '/boi/historia'
    | '/boi/itens'
    | '/boi/toadas'
    | '/loja/carrinho'
    | '/painel/'
    | '/agenda/'
    | '/loja/'
    | '/noticias/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/health'
    | '/sitemap.xml'
    | '/entrar'
    | '/$'
    | '/contato'
    | '/festival'
    | '/privacidade'
    | '/socio'
    | '/tema'
    | '/termos'
    | '/visite'
    | '/boi/galeria'
    | '/boi/historia'
    | '/boi/itens'
    | '/boi/toadas'
    | '/loja/carrinho'
    | '/painel'
    | '/agenda'
    | '/loja'
    | '/noticias'
  id:
    | '__root__'
    | '/_authentication'
    | '/_private'
    | '/_public'
    | '/health'
    | '/sitemap.xml'
    | '/_authentication/entrar'
    | '/_public/$'
    | '/_public/contato'
    | '/_public/festival'
    | '/_public/privacidade'
    | '/_public/socio'
    | '/_public/tema'
    | '/_public/termos'
    | '/_public/visite'
    | '/_public/'
    | '/_public/boi/galeria'
    | '/_public/boi/historia'
    | '/_public/boi/itens'
    | '/_public/boi/toadas'
    | '/_public/loja/carrinho'
    | '/_private/painel/'
    | '/_public/agenda/'
    | '/_public/loja/'
    | '/_public/noticias/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticationLayoutRoute: typeof AuthenticationLayoutRouteWithChildren
  PrivateLayoutRoute: typeof PrivateLayoutRouteWithChildren
  PublicLayoutRoute: typeof PublicLayoutRouteWithChildren
  HealthRoute: typeof HealthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authentication': {
      id: '/_authentication'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticationLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private': {
      id: '/_private'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PrivateLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authentication/entrar': {
      id: '/_authentication/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof AuthenticationEntrarRouteImport
      parentRoute: typeof AuthenticationLayoutRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_public/$': {
      id: '/_public/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof PublicSplatRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_public/contato': {
      id: '/_public/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof PublicContatoRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_public/festival': {
      id: '/_public/festival'
      path: '/festival'
      fullPath: '/festival'
      preLoaderRoute: typeof PublicFestivalRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_public/privacidade': {
      id: '/_public/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PublicPrivacidadeRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_public/socio': {
      id: '/_public/socio'
      path: '/socio'
      fullPath: '/socio'
      preLoaderRoute: typeof PublicSocioRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_public/tema': {
      id: '/_public/tema'
      path: '/tema'
      fullPath: '/tema'
      preLoaderRoute: typeof PublicTemaRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_public/termos': {
      id: '/_public/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof PublicTermosRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_public/visite': {
      id: '/_public/visite'
      path: '/visite'
      fullPath: '/visite'
      preLoaderRoute: typeof PublicVisiteRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_private/painel/': {
      id: '/_private/painel/'
      path: '/painel'
      fullPath: '/painel/'
      preLoaderRoute: typeof PrivatePainelIndexRouteImport
      parentRoute: typeof PrivateLayoutRoute
    }
    '/_public/agenda/': {
      id: '/_public/agenda/'
      path: '/agenda'
      fullPath: '/agenda/'
      preLoaderRoute: typeof PublicAgendaIndexRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_public/boi/galeria': {
      id: '/_public/boi/galeria'
      path: '/boi/galeria'
      fullPath: '/boi/galeria'
      preLoaderRoute: typeof PublicBoiGaleriaRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_public/boi/historia': {
      id: '/_public/boi/historia'
      path: '/boi/historia'
      fullPath: '/boi/historia'
      preLoaderRoute: typeof PublicBoiHistoriaRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_public/boi/itens': {
      id: '/_public/boi/itens'
      path: '/boi/itens'
      fullPath: '/boi/itens'
      preLoaderRoute: typeof PublicBoiItensRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_public/boi/toadas': {
      id: '/_public/boi/toadas'
      path: '/boi/toadas'
      fullPath: '/boi/toadas'
      preLoaderRoute: typeof PublicBoiToadasRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_public/loja/': {
      id: '/_public/loja/'
      path: '/loja'
      fullPath: '/loja/'
      preLoaderRoute: typeof PublicLojaIndexRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_public/loja/carrinho': {
      id: '/_public/loja/carrinho'
      path: '/loja/carrinho'
      fullPath: '/loja/carrinho'
      preLoaderRoute: typeof PublicLojaCarrinhoRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_public/noticias/': {
      id: '/_public/noticias/'
      path: '/noticias'
      fullPath: '/noticias/'
      preLoaderRoute: typeof PublicNoticiasIndexRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
  }
}

interface AuthenticationLayoutRouteChildren {
  AuthenticationEntrarRoute: typeof AuthenticationEntrarRoute
}

const AuthenticationLayoutRouteChildren: AuthenticationLayoutRouteChildren = {
  AuthenticationEntrarRoute: AuthenticationEntrarRoute,
}

const AuthenticationLayoutRouteWithChildren =
  AuthenticationLayoutRoute._addFileChildren(AuthenticationLayoutRouteChildren)

interface PrivateLayoutRouteChildren {
  PrivatePainelIndexRoute: typeof PrivatePainelIndexRoute
}

const PrivateLayoutRouteChildren: PrivateLayoutRouteChildren = {
  PrivatePainelIndexRoute: PrivatePainelIndexRoute,
}

const PrivateLayoutRouteWithChildren = PrivateLayoutRoute._addFileChildren(
  PrivateLayoutRouteChildren,
)

interface PublicLayoutRouteChildren {
  PublicSplatRoute: typeof PublicSplatRoute
  PublicContatoRoute: typeof PublicContatoRoute
  PublicFestivalRoute: typeof PublicFestivalRoute
  PublicPrivacidadeRoute: typeof PublicPrivacidadeRoute
  PublicSocioRoute: typeof PublicSocioRoute
  PublicTemaRoute: typeof PublicTemaRoute
  PublicTermosRoute: typeof PublicTermosRoute
  PublicVisiteRoute: typeof PublicVisiteRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicBoiGaleriaRoute: typeof PublicBoiGaleriaRoute
  PublicBoiHistoriaRoute: typeof PublicBoiHistoriaRoute
  PublicBoiItensRoute: typeof PublicBoiItensRoute
  PublicBoiToadasRoute: typeof PublicBoiToadasRoute
  PublicLojaCarrinhoRoute: typeof PublicLojaCarrinhoRoute
  PublicAgendaIndexRoute: typeof PublicAgendaIndexRoute
  PublicLojaIndexRoute: typeof PublicLojaIndexRoute
  PublicNoticiasIndexRoute: typeof PublicNoticiasIndexRoute
}

const PublicLayoutRouteChildren: PublicLayoutRouteChildren = {
  PublicSplatRoute: PublicSplatRoute,
  PublicContatoRoute: PublicContatoRoute,
  PublicFestivalRoute: PublicFestivalRoute,
  PublicPrivacidadeRoute: PublicPrivacidadeRoute,
  PublicSocioRoute: PublicSocioRoute,
  PublicTemaRoute: PublicTemaRoute,
  PublicTermosRoute: PublicTermosRoute,
  PublicVisiteRoute: PublicVisiteRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicBoiGaleriaRoute: PublicBoiGaleriaRoute,
  PublicBoiHistoriaRoute: PublicBoiHistoriaRoute,
  PublicBoiItensRoute: PublicBoiItensRoute,
  PublicBoiToadasRoute: PublicBoiToadasRoute,
  PublicLojaCarrinhoRoute: PublicLojaCarrinhoRoute,
  PublicAgendaIndexRoute: PublicAgendaIndexRoute,
  PublicLojaIndexRoute: PublicLojaIndexRoute,
  PublicNoticiasIndexRoute: PublicNoticiasIndexRoute,
}

const PublicLayoutRouteWithChildren = PublicLayoutRoute._addFileChildren(
  PublicLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticationLayoutRoute: AuthenticationLayoutRouteWithChildren,
  PrivateLayoutRoute: PrivateLayoutRouteWithChildren,
  PublicLayoutRoute: PublicLayoutRouteWithChildren,
  HealthRoute: HealthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
